language: java

env:
  - DATE = `date + "%Y-%m-%d-%H%M"`

jobs:
  inclue:
    - stage: "security_application"
      name: "build"
      script: mvn clean package
    - stage: "build test"
      name: "test war"
      script: ls -l target | grep --color=always verademo verademo.war