language: java

env:
  - DATE = `date + "%Y-%m-%d-%H%M"`

jobs:
  inclue:
    - stage: "Build Java app with Maven"
      name: "build"
      script: mvn clean package
    - stage: "Veracode SCA - Software Composition Analisys"
      name: "Veracode SCA - Software Composition Analisys"
      script: 
        - curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan  --update-advisor || true
    - stage: "Veracode SAST - Pipeline Scan"
      name: "Veracode SAST - Pipeline Scan"
      before_script:
        - curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
        - unzip -o pipeline-scan-LATEST.zip
      script:
        - java -jar pipeline-scan.jar -vid $VERACODE_ID -vkey $VERACODE_KEY -f target/verademo.war --issue_details true || true