language: java

env:
  - DATE = `date + "%Y-%m-%d-%H%M"`

jobs:
  inclue:
    - stage: "build java with maven"
      name: "build"
      script: mvn clean package
    - stage: "build test"
      name: "test war"
      script: 
        - ls -l
        - ls -l target
    - stage: "Veracode SAST - Pipeline Scan"
      name: "Veracode SAST - Pipeline Scan"
      before_script:
        - curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
        - unzip -o pipeline-scan-LATEST.zip
      script:
        - java -jar pipeline-scan.jar -vid $(VERACODE_ID) -vkey $(VERACODE_KEY) -f target/verademo.war --isue_details