language: java

env:
  - DATE = `date + "%Y-%m-%d-%H%M"`

jobs:
  inclue:
    - stage: "build java with maven"
      name: "build"
      script: mvn clean package
    - stage: "build test"
      name: "test war"
      script: 
        - ls -l
        - ls -l target