language: java

env:
  - DATE = `date + "%Y-%m-%d-%H%M"`

jobs:
  inclue:
    - stage: "Build Java app with Maven"
      name: "build"
      script: mvn clean package
    - stage: "Veracode SAST - Sandbox Scan"
      name: "Veracode SAST - Sandbox Scan"
      before_script:
        - wget -q -O veracode-wrapper-api.jar https://search.maven.org/remotecontent?filepath=com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/21.9.8.2/vosp-api-wrappers-java-21.9.8.2.jar
      script: |
        - java -jar veracode-wrapper-api.jar 
          -vid $VERACODE_ID 
          -vkey $VERACODE_KEY 
          -action uploadandscan 
          -appname "Java-VeraDemo"
          -createprofile false 
          -filepath target/verademo.war 
          -createsandbox false 
          -sandboxname "SANDBOX_1" 
          -deleteincompletescan true 
          -scanpollinginterval 60 
          -version "$TRAVIS_JOB_ID - $TRAVIS_JOB_NUMBER $DATE" 
          -scantimeout 60