version: 2.1

jobs:
  build:
    docker:
      # The primary container is an instance of the first image listed. The job's commands run in this container.
      - image: maven:3.6.3-openjdk-8
    working_directory: ~/target
    steps:
      - checkout
      - run:
          name: Run Maven
          command: | 
            'mvn compile package'
            ls -lah /target | grep '*.war'
      # keep the files around for the scan job
      - persist_to_workspace:
          root: ./
          paths:
            - target
            - ./